import old meta-inf

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,10 +1,17 @@
 #!/sbin/sh
 # AnyKernel2 Backend
 # osm0sis @ xda-developers
+{
+if [ ! getprop ro.treble.enabled ]; then
+    echo "This version Of Catalyst kernel only support Treble ROM!"
+	echo "Flash NON-Treble Version!"
+    exit 0
+fi
+}
 
 OUTFD=/proc/self/fd/$2;
-ZIP="$3";
-DIR=`dirname "$ZIP"`;
+ZIPFILE="$3";
+DIR=`dirname "$ZIPFILE"`;
 
 ui_print() {
   until [ ! "$1" ]; do
@@ -13,47 +20,91 @@ ui_print() {
   done;
 }
 show_progress() { echo "progress $1 $2" > $OUTFD; }
-set_perm_recursive() {
-  dirs=$(echo $* | $bb awk '{ print substr($0, index($0,$5)) }');
-  for i in $dirs; do
-    $bb chown -R $1:$2 $i;
-    find "$i" -type d -exec chmod $3 {} +;
-    find "$i" -type f -exec chmod $4 {} +;
-  done;
-}
-file_getprop() { grep "^$2" "$1" | cut -d= -f2; }
-cleanup() { rm -rf /tmp/anykernel; }
-if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort)" == 1 ]; then
-    abort() { ui_print "$*"; cleanup; umount /system; umount /data; exit 1; }
-  else
-    abort() { ui_print "$*"; umount /system; umount /data; exit 1; }
+file_getprop() { grep "^$2=" "$1" | cut -d= -f2; }
+if [ ! "$(getprop 2>/dev/null)" ]; then
+  getprop() {
+    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
+    test "$propval" || local propval="$(file_getprop $root/system/build.prop $1 2>/dev/null)";
+    test "$propval" && echo "$propval" || echo "";
+  }
 fi;
+cleanup() { rm -rf /tmp/anykernel; }
+debugging() {
+  case $(basename "$ZIPFILE" .zip) in
+    *-debugging)
+      ui_print " ";
+      ui_print "Creating debugging archive in zip directory...";
+      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
+    ;;
+  esac;
+}
+abort() {
+  ui_print "$*";
+  debugging;
+  if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
+    cleanup;
+  fi;
+  umount /system;
+  umount /vendor 2>/dev/null;
+  umount /data 2>/dev/null;
+  exit 1;
+}
 
 show_progress 1.34 4;
 ui_print " ";
 cleanup;
 mkdir -p /tmp/anykernel/bin;
 cd /tmp/anykernel;
-unzip -o "$ZIP";
+unzip -o "$ZIPFILE";
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
-chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
 bb=/tmp/anykernel/tools/busybox;
+chmod 755 $bb;
+$bb chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
 
-ui_print "       **********************************";
-ui_print "       * Spectrum user profile injector *";
-ui_print "       *           by frap129           *";
-ui_print "       **********************************";
+if [ -f /tmp/anykernel/banner ]; then
+  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
+    ui_print "$line";
+  done < /tmp/anykernel/banner;
+  ui_print " ";
+  ui_print " ";
+fi;
+
+ui_print "$(file_getprop /tmp/anykernel/anykernel.sh kernel.string)";
+if [ -f /tmp/anykernel/version ]; then
+  ui_print " ";
+  ui_print "$(cat /tmp/anykernel/version)";
+  ui_print " ";
+fi;
 ui_print " ";
-ui_print "        Made using AnyKernel2 by osm0sis";
+ui_print "AnyKernel2 by osm0sis @ xda-developers";
 ui_print " ";
-umount /system;
+ui_print " ";
+
+umount /system 2>/dev/null;
+umount /vendor 2>/dev/null;
 mount -o ro -t auto /system;
-mount /data;
+mount -o ro -t auto /vendor 2>/dev/null;
+mount /data 2>/dev/null;
 test -f /system/system/build.prop && root=/system;
 
-ui_print "Injecting configurable Spectrum support...";
+if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
+  ui_print "Checking device...";
+  for i in 1 2 3 4 5; do
+    testname="$(file_getprop /tmp/anykernel/anykernel.sh device.name$i)";
+    if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
+      ui_print "$testname";
+      match=1;
+    fi;
+  done;
+  ui_print " ";
+  if [ "$match" != 1 ]; then
+    abort "Unsupported device. Aborting...";
+  fi;
+fi;
+
+ui_print "Installing...";
 for i in $($bb --list); do
   $bb ln -s $bb /tmp/anykernel/bin/$i;
 done;
@@ -65,11 +116,45 @@ if [ $? != "0" ]; then
   abort;
 fi;
 
+if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
+  ui_print " ";
+  ui_print "Pushing modules...";
+  mount -o rw,remount -t auto /system;
+  mount -o rw,remount -t auto /vendor 2>/dev/null;
+  cd /tmp/anykernel/modules;
+  for module in $(find . -name '*.ko'); do
+    case $module in
+      */system/*) modtarget=$root/$module;;
+      *) modtarget=/$module;;
+    esac;
+    if [ ! -e $modtarget ]; then
+      case $module in
+        */vendor/*) mod=vendor;;
+        *) mod=system;;
+      esac;
+    fi;
+    mkdir -p $(dirname $modtarget);
+    $bb cp -rLf $module $modtarget;
+    $bb chown 0:0 $modtarget;
+    $bb chmod 644 $modtarget;
+    if [ "$mod" ]; then
+      chcon "u:object_r:${mod}_file:s0" $modtarget;
+    fi;
+  done;
+  cd /tmp/anykernel;
+  mount -o ro,remount -t auto /system;
+  mount -o ro,remount -t auto /vendor 2>/dev/null;
+fi;
+
+debugging;
+
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
 umount /system;
-umount /data;
+umount /vendor 2>/dev/null;
+umount /data 2>/dev/null;
+ui_print " ";
 ui_print " ";
 ui_print "Done!";
